---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/spruce

inputs:
- name: config
- name: pipeline

outputs:
- name: output

params:
  SETTINGS: config/settings.yml

run:
  path: pipeline/ci/scripts/generate-configs.sh
