---

jobs:
- name: sandbox
  plan:
    - aggregate:
      - get: config
        resource: sandbox-config
        trigger: true
      - get: pipeline
    - task: generate-configs
      file: pipeline/ci/tasks/generate-configs.yml
      params:
        VAULT_ADDR: ((vault.address))
        VAULT_TOKEN: ((vault.token))
        SETTINGS: ((sandbox.settings))
    - task: use-configs
      file: pipeline/ci/tasks/use-configs.yml
    - task: delete-configs
      file: pipeline/ci/tasks/delete-configs.yml
- name: nonprod
  plan:
    - aggregate:
      - get: config
        resource: nonprod-config
        trigger: true
      - get: pipeline
    - task: generate-configs
      file: pipeline/ci/tasks/generate-configs.yml
      params:
        VAULT_ADDR: ((vault.address))
        VAULT_TOKEN: ((vault.token))
        SETTINGS: ((nonprod.settings))
    - task: use-configs
      file: pipeline/ci/tasks/use-configs.yml
    - task: delete-configs
      file: pipeline/ci/tasks/delete-configs.yml

resources:
- name: pipeline
  type: git
  source:
    uri: https://github.com/mcarey-solstice/travel-agent-deployment

- name: sandbox-config
  type: git
  source:
    uri: https://github.com/mcarey-solstice/travel-agent-configs
    path: sandbox

- name: nonprod-config
  type: git
  source:
    uri: https://github.com/mcarey-solstice/travel-agent-configs
    path: nonprod
